# Generated by Django 4.2.6 on 2023-10-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Привязка тега', 'verbose_name_plural': 'Привязки тэгов'},
        ),
    ]
